import assert from 'node:assert/strict';
import {createImageCache,createSceneGate,artSource} from './story-media.js';
const deferred=()=>{let resolve,reject;const promise=new Promise((ok,no)=>{resolve=ok;reject=no;});return {promise,resolve,reject};};
const images=[];
const cache=createImageCache({createImage:()=>{const decoded=deferred();const image={naturalWidth:1280,decoded,decode:()=>decoded.promise};images.push(image);return image;},timeoutMs:1000});
const events=[];let retry;
const gate=createSceneGate(cache,{pending:()=>events.push('pending'),ready:()=>events.push('ready'),error:fn=>{events.push('error');retry=fn;}});
const first=gate.show(['one.webp'],()=>events.push('first text + image'));
const duplicate=cache.load('one.webp','low');
assert.equal(images.length,1,'preload and foreground share one request');
images[0].onload();await Promise.resolve();assert.deepEqual(events,['pending'],'text must wait for decoding');
const second=gate.show(['two.webp'],()=>events.push('second text + image'));
images[1].onload();images[1].decoded.resolve();await second;
images[0].decoded.resolve();await first;await duplicate;
assert.equal(events.includes('first text + image'),false,'a late image must not restore an old scene');
assert.equal(events.at(-1),'second text + image');assert.equal(gate.busy,false);
let instant=false;gate.show(['two.webp'],()=>{instant=true;});assert.equal(instant,true,'cached scenes have no delay');
const cancelled=gate.show(['three.webp'],()=>events.push('cancelled'));gate.cancel();images[2].onload();images[2].decoded.resolve();await cancelled;assert.equal(events.includes('cancelled'),false);
const failed=gate.show(['broken.webp'],()=>events.push('recovered'));images[3].onerror();await failed;assert.equal(events.at(-1),'error');
retry();assert.equal(images.length,5,'retry starts a fresh request');images[4].onload();images[4].decoded.resolve();await cache.load('broken.webp');await Promise.resolve();assert.ok(events.includes('recovered'));
const timeoutCache=createImageCache({createImage:()=>({}),timeoutMs:5});await assert.rejects(timeoutCache.load('never.webp'));
assert.equal(artSource('test','thumb'),'art/test-360.webp');
console.log('PASS image loading: shared preloads, decode-before-render, late navigation, cache, cancellation, retry and timeout.');
